# This workflow will install Python dependencies, run tests and lint on every
# push or PR change

name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop build in case of failure
        flake8 . --show-source --statistics
    - name: Test with pytest
      run: |
        pytest
