# This workflow will install Python dependencies, build installation artifact
# and push it to the GitHub release

name: release

on:
  release:
    types: [created]
    branches: [ main ]

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build artifact
      run: python setup.py py2app
    - name: Zip artifact
      run: zip -r release.zip ./dist/macos-gitlab.app
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip
